version: '3.5'

services:
  postgres:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: test@123
      POSTGRES_DB: twitter
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped


networks:
  postgres:
    driver: bridge

volumes:
  postgres: